global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["bo6for7sk1.execute-api.us-east-1.amazonaws.com"]
    scheme: https
    metrics_path: /dev/metrics
